### ISSUE TITLE
Login function

### ISSUE THREAD

**Issue by thailqcomartek** [comartek/fs-clone-tinwin-customer#26]
https://github.com/comartek/fs-clone-tinwin-customer/pull/28

**Comment by phuongna-comartek** [comment]
check comment @thailqcomartek

**Comment by thailqcomartek** [comment]
E sửa mấy cái a bảo r @phuongna-comartek

**Comment by thailqcomartek** [comment]
E sửa thành useRef rồi @phuongna-comartek
